-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 16:01:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS FIXAGRO DEFAULT CHARACTER SET utf8 ;
USE FIXAGRO ;
-- -----------------------------------------------------
-- Table persona
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS persona (
  id INT auto_increment unique,
  nombre VARCHAR(45) NOT NULL,
  apellido VARCHAR(45) NOT NULL,
  direccion VARCHAR(45) NOT NULL,
  municipio VARCHAR(45) NOT NULL,
  departamento VARCHAR(45) NOT NULL,
  telefono varchar(20) NOT NULL,
  email VARCHAR(60) NOT NULL,
  contrasena VARCHAR(200) NOT NULL,
  estado ENUM("ACTIVO", "INACTIVO"),
  fecha_registro DATE NOT NULL,
  tipo_persona ENUM("CLIENTE", "TECNICO") NOT NULL,
  avatar TEXT(10000) NOT NULL,
  PRIMARY KEY (id)
)ENGINE = InnoDB;
-- -----------------------------------------------------

-- Table tecnico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS tecnico (
  id_tecnico INT NOT NULL,
  experiencia_lab VARCHAR(300) NOT NULL,
  profesion VARCHAR(45) NOT NULL,
  FOREIGN KEY (id_tecnico)  REFERENCES persona (id)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table maquinas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS maquinas (
  id_maquina INT NOT NULL AUTO_INCREMENT,
  tipo_maquina VARCHAR(50) NOT NULL,
  modelo VARCHAR(45) NOT NULL,
  marca VARCHAR(50) NOT NULL,
  img TEXT(10000) NOT NULL,
  id_usuario INT NOT NULL,
  fecha_creacion DATE NOT NULL,
  estado ENUM("ACTIVO", "INACTIVO") NOT NULL,
  PRIMARY KEY (id_maquina),
FOREIGN KEY (id_usuario) REFERENCES persona (id)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table publicaciones
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS publicaciones (
  id_publicacion INT NOT NULL AUTO_INCREMENT,
  id_maquina INT NOT NULL,
  id_usuario INT NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  fecha_creacion DATETIME NOT NULL,
  fecha_modificacion DATETIME NOT NULL,
  estado ENUM("ACTIVO", "EN PROCESO", "FINALIZADO") NOT NULL,
  PRIMARY KEY (id_publicacion),
 FOREIGN KEY (id_usuario) REFERENCES persona (id),
 FOREIGN KEY (id_maquina) REFERENCES maquinas (id_maquina)
 )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table informe_tec
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS informe_tec (
  id_publicacion INT NOT NULL AUTO_INCREMENT,
  id_usuario_tec INT NOT NULL,
  problema_tecnico VARCHAR(100) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  fecha_Aceptacion DATE NOT NULL,
  fechas_finalizacion DATE NOT NULL,
  PRIMARY KEY (id_publicacion),
  FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion),
  FOREIGN KEY (id_usuario_tec) REFERENCES persona (id)
)ENGINE = InnoDB;

CREATE TABLE ofertas (
id INT AUTO_INCREMENT PRIMARY KEY,
id_publicacion INT,
id_tecnico INT,
id_persona INT,
fecha_oferta DATETIME,
fec_actu DATETIME,
estado ENUM("ENVIADA", "RECHAZA", "ACEPTADA")
);

CREATE TABLE chat_ofertas (
id INT AUTO_INCREMENT PRIMARY KEY,
id_publicacion INT,
destinatario int(11),
remitente int(11),
mensaje VARCHAR(10000),
fecha_envio DATETIME
);

CREATE TABLE `trabajos` (
  id_trabajo int(50) NOT NULL,
  id_tecnico int(50) NOT NULL,
  id_maquina int(50) NOT NULL,
  estado varchar(50) NOT NULL,
  fecha_creacion datetime(6) NOT NULL,
  fecha_finalizacion datetime(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `trabajos`
  ADD PRIMARY KEY (`id_trabajo`),
  ADD KEY `id_tecnico` (`id_tecnico`),
  ADD KEY `id_maquina` (`id_maquina`);

  ALTER TABLE `trabajos`
  MODIFY `id_trabajo` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

  ALTER TABLE `trabajos`
  ADD CONSTRAINT `trabajos_ibfk_1` FOREIGN KEY (`id_tecnico`) REFERENCES `persona` (`id`) ON UPDATE CASCADE,
  ADD CONSTRAINT `trabajos_ibfk_2` FOREIGN KEY (`id_maquina`) REFERENCES `maquinas` (`id_maquina`) ON UPDATE CASCADE;
COMMIT;